version: '3.9'

services:
  redis:
    image: redis:alpine
    container_name: integration-tests-redis
    ports:
      - '6379'
  db:
    image: postgres:14
    restart: always
    container_name: integration-tests-database
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
