export type EntityName =
  | 'Customer'
  | 'Market'
  | 'Market sub-account'
  | 'City'
  | 'Item'
  | 'Product'
  | 'Product(s)'
  | 'Order'
  | 'Invoice'
  | 'Payout'
  | 'Review'
  | 'Address'
  | 'Card'
  | 'Bank account'
  | 'OTP'
  | 'Session'
  | 'Document'
  | 'Postal Code'
  | 'Location';
